// AUTOGENERATED FROM PICO_CONFIG_HEADER_FILES and then PICO_<PLATFORM>_CONFIG_HEADER_FILES
// DO NOT EDIT!


// based on PICO_CONFIG_HEADER_FILES:

#include "../../pico-sdk/src/boards/include/boards/solderparty_rp2350_stamp_xl.h"

// based on PICO_RP2350_RISCV_CONFIG_HEADER_FILES:
